export const detailsData = {
  id: 1753434,
  objectID: 1753434,
  ownerID: 792123,
  userExternalID: "792123",
  sourceID: 1,
  state: "inactive",
  geography: {
    lat: 25.053822,
    lng: 55.212933,
  },
  purpose: "for-rent",
  price: 8785,
  product: "premium",
  productLabel: "default",
  rentFrequency: "monthly",
  referenceNumber: "204M",
  permitNumber: "JUM-EMI-4JLJT",
  projectNumber: null,
  title:
    "BIG OFFER!!! FOR IMMEDIATE BOOKING! AMAZING AND COZY 1 BEDROOM  APARTMENT IN THE HEART OF JVC",
  title_l1:
    "BIG OFFER!!! FOR IMMEDIATE BOOKING! AMAZING AND COZY 1 BEDROOM  APARTMENT IN THE HEART OF JVC",
  title_l2:
    "位于朱美拉环形村(JVC)，JVC第12区，阿联酋花园 1 卧室的公寓 8785 AED - 4594156",
  title_l3:
    "Квартира в Джумейра Вилладж Серкл (ДЖВС)，JVC Дистрикт 12，Эмирейтс Гарденс, 1 спальня, 8785 AED - 4594156",
  description:
    "Your Keys Holiday Homes would like to present to you a beautiful and cozy 1 bedroom apartment with large balcony with pool view in the heart of Jumeirah Village Circle, Dubai. \n\nThis apartment comes with a complete kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune!). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nAbout the area: \nLocated between Sheikh Zayed and the Emirates Road, Jumeirah Village Circle boasts a promising location just in the heart of Dubai with its lush landscaping, water areas, parks and green features Jumeirah Village Circle are of most demand in the whole development.  \n\nPharmacy and grocery store available on-site.  \n\n17 mins drive to the beach/Dubai Marina\n20 mins drive to Downtown/Dubai Mall\n\nINCLUSIONS:\nAll bills ( Dewa, WIFI, AC and Gas)\nAccess to large swimming pool and gym\nOne free covered parking space\n**Weekly cleaning with replacing all linens and towels (with charges)\nTERM &amp; CONDITIONS\n===============================\nSecurity Deposit : 2500 AED per stay (cash)\n* Rates vary according to availability and seasons  \nDTCM fees: 10 AED per night\nAgency Fees : Applicable \nLimited period offer!!!\n\nNote: No Commission. No Hidden Fees. \n\nPre-Payment/ Cancellation\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date once we agreed\nThis pre-payment is not refundable because based on it we will cancel all inquiries. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nWe have the Admin team, Maintenance team and Cleaning team available to help you with your stay be a comfortable one.",
  description_l1:
    "Your Keys Holiday Homes would like to present to you a beautiful and cozy 1 bedroom apartment with large balcony with pool view in the heart of Jumeirah Village Circle, Dubai. \n\nThis apartment comes with a complete kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune!). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nAbout the area: \nLocated between Sheikh Zayed and the Emirates Road, Jumeirah Village Circle boasts a promising location just in the heart of Dubai with its lush landscaping, water areas, parks and green features Jumeirah Village Circle are of most demand in the whole development.  \n\nPharmacy and grocery store available on-site.  \n\n17 mins drive to the beach/Dubai Marina\n20 mins drive to Downtown/Dubai Mall\n\nINCLUSIONS:\nAll bills ( Dewa, WIFI, AC and Gas)\nAccess to large swimming pool and gym\nOne free covered parking space\n**Weekly cleaning with replacing all linens and towels (with charges)\nTERM &amp; CONDITIONS\n===============================\nSecurity Deposit : 2500 AED per stay (cash)\n* Rates vary according to availability and seasons  \nDTCM fees: 10 AED per night\nAgency Fees : Applicable \nLimited period offer!!!\n\nNote: No Commission. No Hidden Fees. \n\nPre-Payment/ Cancellation\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date once we agreed\nThis pre-payment is not refundable because based on it we will cancel all inquiries. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nWe have the Admin team, Maintenance team and Cleaning team available to help you with your stay be a comfortable one.",
  description_l2:
    "Your Keys Holiday Homes would like to present to you a beautiful and cozy 1 bedroom apartment with large balcony with pool view in the heart of Jumeirah Village Circle, Dubai. \n\nThis apartment comes with a complete kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune!). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nAbout the area: \nLocated between Sheikh Zayed and the Emirates Road, Jumeirah Village Circle boasts a promising location just in the heart of Dubai with its lush landscaping, water areas, parks and green features Jumeirah Village Circle are of most demand in the whole development.  \n\nPharmacy and grocery store available on-site.  \n\n17 mins drive to the beach/Dubai Marina\n20 mins drive to Downtown/Dubai Mall\n\nINCLUSIONS:\nAll bills ( Dewa, WIFI, AC and Gas)\nAccess to large swimming pool and gym\nOne free covered parking space\n**Weekly cleaning with replacing all linens and towels (with charges)\nTERM &amp; CONDITIONS\n===============================\nSecurity Deposit : 2500 AED per stay (cash)\n* Rates vary according to availability and seasons  \nDTCM fees: 10 AED per night\nAgency Fees : Applicable \nLimited period offer!!!\n\nNote: No Commission. No Hidden Fees. \n\nPre-Payment/ Cancellation\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date once we agreed\nThis pre-payment is not refundable because based on it we will cancel all inquiries. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nWe have the Admin team, Maintenance team and Cleaning team available to help you with your stay be a comfortable one.",
  description_l3:
    "Your Keys Holiday Homes would like to present to you a beautiful and cozy 1 bedroom apartment with large balcony with pool view in the heart of Jumeirah Village Circle, Dubai. \n\nThis apartment comes with a complete kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune!). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nAbout the area: \nLocated between Sheikh Zayed and the Emirates Road, Jumeirah Village Circle boasts a promising location just in the heart of Dubai with its lush landscaping, water areas, parks and green features Jumeirah Village Circle are of most demand in the whole development.  \n\nPharmacy and grocery store available on-site.  \n\n17 mins drive to the beach/Dubai Marina\n20 mins drive to Downtown/Dubai Mall\n\nINCLUSIONS:\nAll bills ( Dewa, WIFI, AC and Gas)\nAccess to large swimming pool and gym\nOne free covered parking space\n**Weekly cleaning with replacing all linens and towels (with charges)\nTERM &amp; CONDITIONS\n===============================\nSecurity Deposit : 2500 AED per stay (cash)\n* Rates vary according to availability and seasons  \nDTCM fees: 10 AED per night\nAgency Fees : Applicable \nLimited period offer!!!\n\nNote: No Commission. No Hidden Fees. \n\nPre-Payment/ Cancellation\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date once we agreed\nThis pre-payment is not refundable because based on it we will cancel all inquiries. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nWe have the Admin team, Maintenance team and Cleaning team available to help you with your stay be a comfortable one.",
  externalID: "4594156",
  slug: "details_4594156",
  slug_l1: "details_4594156",
  slug_l2: "details_4594156",
  slug_l3: "details_4594156",
  location: [
    {
      id: 1,
      level: 0,
      externalID: "5001",
      name: "UAE",
      name_l1: "الإمارات",
      name_l2: "阿联酋",
      name_l3: "ОАЭ",
      slug: "/uae",
      slug_l1: "/uae",
      slug_l2: "/uae",
      slug_l3: "/uae",
    },
    {
      id: 2,
      level: 1,
      externalID: "5002",
      name: "Dubai",
      name_l1: "دبي",
      name_l2: "迪拜",
      name_l3: "Дубай",
      slug: "/dubai",
      slug_l1: "/dubai",
      slug_l2: "/dubai",
      slug_l3: "/dubai",
    },
    {
      id: 59,
      level: 2,
      externalID: "5416",
      name: "Jumeirah Village Circle (JVC)",
      name_l1: "قرية جميرا الدائرية",
      name_l2: "朱美拉环形村(JVC)",
      name_l3: "Джумейра Вилладж Серкл (ДЖВС)",
      slug: "/dubai/jumeirah-village-circle-jvc",
      slug_l1: "/dubai/jumeirah-village-circle-jvc",
      slug_l2: "/dubai/jumeirah-village-circle-jvc",
      slug_l3: "/dubai/jumeirah-village-circle-jvc",
      type: "neighbourhood",
    },
    {
      id: 1881,
      level: 3,
      externalID: "9536",
      name: "JVC District 12",
      name_l1: "الضاحية 12",
      name_l2: "JVC第12区",
      name_l3: "JVC Дистрикт 12",
      slug: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l1: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l2: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l3: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      type: "neighbourhood",
    },
    {
      id: 717,
      level: 4,
      externalID: "5422",
      name: "Emirates Gardens",
      name_l1: "حدائق الإمارات",
      name_l2: "阿联酋花园",
      name_l3: "Эмирейтс Гарденс",
      slug: "/dubai/jumeirah-village-circle-jvc/jvc-district-12/emirates-gardens",
      slug_l1:
        "/dubai/jumeirah-village-circle-jvc/jvc-district-12/emirates-gardens",
      slug_l2:
        "/dubai/jumeirah-village-circle-jvc/jvc-district-12/emirates-gardens",
      slug_l3:
        "/dubai/jumeirah-village-circle-jvc/jvc-district-12/emirates-gardens",
    },
  ],
  category: [
    {
      id: 1,
      level: 0,
      externalID: "1",
      name: "Residential",
      name_l1: "سكني",
      name_l2: "居住物业",
      name_l3: "Жилые",
      slug: "residential",
      slug_l1: "residential",
      slug_l2: "residential",
      slug_l3: "residential",
      nameSingular: "Residential",
      nameSingular_l1: "سكني",
      nameSingular_l2: "居住物业",
      nameSingular_l3: "Жилые",
    },
    {
      id: 2,
      level: 1,
      externalID: "4",
      name: "Apartments",
      name_l1: "شقق",
      name_l2: "公寓",
      name_l3: "Апартаменты",
      slug: "apartments",
      slug_l1: "apartments",
      slug_l2: "apartments",
      slug_l3: "apartments",
      nameSingular: "Apartment",
      nameSingular_l1: "شقة",
      nameSingular_l2: "公寓",
      nameSingular_l3: "Квартира",
    },
  ],
  createdAt: 1612524492,
  approvedAt: 1612524492,
  updatedAt: 1697140886,
  touchedAt: 1697140925.256017,
  reactivatedAt: 1675839532.190267,
  rooms: 1,
  baths: 2,
  area: 91.69530048,
  score: 100,
  score_l1: 100,
  score_l2: 75,
  score_l3: 75,
  coverPhoto: {
    id: 111224770,
    externalID: "109566550",
    title: null,
    orderIndex: 0,
    nimaScore: 9.432903322295587,
    url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224770/e245ddd62b1747f1891f1506b17688e2",
    main: true,
  },
  photoCount: 20,
  videoCount: 0,
  panoramaCount: 0,
  photos: [
    {
      id: 111224770,
      externalID: "109566550",
      title: null,
      orderIndex: 0,
      nimaScore: 9.432903322295587,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224770/e245ddd62b1747f1891f1506b17688e2",
    },
    {
      id: 111224887,
      externalID: "109566557",
      title: null,
      orderIndex: 1,
      nimaScore: 9.249002995811338,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224887/361e337887f14569b73654e306a796b5",
    },
    {
      id: 106737864,
      externalID: "97202146",
      title: null,
      orderIndex: 2,
      nimaScore: 8.862430429920323,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/106737864/f1215043a52845e790cd845dabdc79a2",
    },
    {
      id: 106737867,
      externalID: "97202149",
      title: null,
      orderIndex: 3,
      nimaScore: 6.004004362470329,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/106737867/fccf702d1e304bc89138200a58e3d405",
    },
    {
      id: 106737871,
      externalID: "97202153",
      title: null,
      orderIndex: 4,
      nimaScore: 8.528184326536575,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/106737871/d285e24546204e6593ef28cffa8530b6",
    },
    {
      id: 111224764,
      externalID: "109566547",
      title: null,
      orderIndex: 5,
      nimaScore: 9.28621088808552,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224764/1c3743eb64904e5aa05e5a684aacccf7",
    },
    {
      id: 111224766,
      externalID: "109566548",
      title: null,
      orderIndex: 6,
      nimaScore: 8.833150405525885,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224766/7f39485195e3448e8a3467eb8e0731eb",
    },
    {
      id: 111224768,
      externalID: "109566549",
      title: null,
      orderIndex: 7,
      nimaScore: 9.17652102797365,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224768/32fba528350a4bffa3bc106172610879",
    },
    {
      id: 111224858,
      externalID: "109566551",
      title: null,
      orderIndex: 8,
      nimaScore: 9.52127119949023,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224858/0df7419843f245b1b587e121b77e8efb",
    },
    {
      id: 111224877,
      externalID: "109566552",
      title: null,
      orderIndex: 9,
      nimaScore: 8.527252048646915,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224877/bedb5574d69e406392c4e407bc4946de",
    },
    {
      id: 111224878,
      externalID: "109566553",
      title: null,
      orderIndex: 10,
      nimaScore: 9.174814502187623,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224878/f10e742cbe2c4af1870bbd0869f93854",
    },
    {
      id: 111224879,
      externalID: "109566554",
      title: null,
      orderIndex: 11,
      nimaScore: 9.809562022070407,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224879/9816b7395d314daf826af65c83126c0b",
    },
    {
      id: 111224880,
      externalID: "109566555",
      title: null,
      orderIndex: 12,
      nimaScore: 9.038036860386455,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224880/b6203f3bf69a498cbfc7e9e695aff989",
    },
    {
      id: 111224886,
      externalID: "109566556",
      title: null,
      orderIndex: 13,
      nimaScore: 9.895108971166763,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224886/ab95def977f4442fa45998bfdaca886d",
    },
    {
      id: 111224888,
      externalID: "109566558",
      title: null,
      orderIndex: 14,
      nimaScore: 8.088853566471244,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224888/430751cd2e4144b8b1dbd257f580f49d",
    },
    {
      id: 111224889,
      externalID: "109566559",
      title: null,
      orderIndex: 15,
      nimaScore: 9.41392204450489,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224889/fd06d34dcea5450ebca583a4a2e6bc8c",
    },
    {
      id: 111224890,
      externalID: "109566560",
      title: null,
      orderIndex: 16,
      nimaScore: 9.441279584283052,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224890/60a1c6dbc68941a394f65ce5abc27cd8",
    },
    {
      id: 111224891,
      externalID: "109566561",
      title: null,
      orderIndex: 17,
      nimaScore: 8.955022605879549,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224891/2f4eebfc862f424ba8c422d661590849",
    },
    {
      id: 111224892,
      externalID: "109566562",
      title: null,
      orderIndex: 18,
      nimaScore: 8.964488665266344,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224892/bf555fb2697448759f3c62fa63fe7949",
    },
    {
      id: 111224893,
      externalID: "109566563",
      title: null,
      orderIndex: 19,
      nimaScore: 9.77512828889536,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/111224893/66db7de8644445c48c7c146876414697",
    },
  ],
  floorPlans: [],
  videos: [],
  panoramas: [],
  amenities: [
    {
      externalGroupID: 9,
      groupRank: 1,
      text: "Features",
      text_l1: "مزايا",
      text_l2: "日托中心",
      text_l3: "Характеристики",
      amenities: [
        {
          text: "Furnished",
          text_l1: "مفروشة",
          text_l2: "配备家具",
          text_l3: "Меблированный",
          value: "1",
          rank: 1,
          slug: "furnished",
          format: "checkbox",
          externalID: 20,
        },
        {
          text: "Centrally Air-Conditioned",
          text_l1: "نظام تبريد مركزي",
          text_l2: "中央空调",
          text_l3: "Центральное кондиционирование",
          value: "1",
          rank: 4,
          slug: "centrally-air-conditioned",
          format: "checkbox",
          externalID: 7,
        },
        {
          text: "Double Glazed Windows",
          text_l1: "نوافذ زجاجية مزدوجة",
          text_l2: "双层玻璃窗",
          text_l3: "Окна с двойным остеклением",
          value: "1",
          rank: 6,
          slug: "double-glazed-windows",
          format: "checkbox",
          externalID: 6,
        },
      ],
    },
    {
      externalGroupID: 5,
      groupRank: 2,
      text: "Building",
      text_l1: "البناء",
      text_l2: "入户大堂",
      text_l3: "Здание",
      amenities: [
        {
          text: "Balcony or Terrace",
          text_l1: "شرفة أو تراس",
          text_l2: "阳台",
          text_l3: "Балкон или терраса",
          value: "1",
          rank: 1,
          slug: "balcony-or-terrace",
          format: "checkbox",
          externalID: 3,
        },
        {
          text: "Lobby in Building",
          text_l1: "ردهة إستقبال",
          text_l2: "入户大堂",
          text_l3: "Лобби в здании",
          value: "1",
          rank: 2,
          slug: "lobby-in-building",
          format: "checkbox",
          externalID: 5,
        },
        {
          text: "Elevators in Building",
          text_l1: "مصاعد",
          text_l2: "电梯",
          text_l3: "Лифты в здании",
          value: "3",
          rank: 3,
          slug: "elevators-in-building",
          format: "number",
          externalID: 16,
        },
        {
          text: "Reception/Waiting Room",
          text_l1: "غرفة استقبال /انتظار",
          text_l2: "桑拿",
          text_l3: "Прием/Зал ожидания",
          value: "1",
          rank: 8,
          slug: "receptionwaiting-room",
          format: "checkbox",
          externalID: 41,
        },
      ],
    },
    {
      externalGroupID: 3,
      groupRank: 3,
      text: "Health and Fitness",
      text_l1: "الصحة و اللياقة",
      text_l2: "阳台",
      text_l3: "Здоровье и Фитнесс",
      amenities: [
        {
          text: "Gym or Health Club",
          text_l1: "صالة رياضية أو نادي صحي",
          text_l2: "健身房或健身俱乐部",
          text_l3: "Тренажерный зал или оздоровительный клуб",
          value: "1",
          rank: 3,
          slug: "gym-or-health-club",
          format: "checkbox",
          externalID: 22,
        },
        {
          text: "Swimming Pool",
          text_l1: "مسبح",
          text_l2: "附近医院",
          text_l3: "Бассейн",
          value: "1",
          rank: 6,
          slug: "swimming-pool",
          format: "checkbox",
          externalID: 45,
        },
      ],
    },
    {
      externalGroupID: 2,
      groupRank: 4,
      text: "Recreation and Family",
      text_l1: "الترفيه والأسرة",
      text_l2: "景观",
      text_l3: "Отдых и семья",
      amenities: [
        {
          text: "Kids Play Area",
          text_l1: "منطقة لعب للأطفال",
          text_l2: "儿童娱乐区",
          text_l3: "Детская игровая площадка",
          value: "1",
          rank: 3,
          slug: "kids-play-area",
          format: "checkbox",
          externalID: 34,
        },
        {
          text: "Lawn or Garden",
          text_l1: "حديقة",
          text_l2: "绿化",
          text_l3: "Газон или сад",
          value: "1",
          rank: 5,
          slug: "lawn-or-garden",
          format: "checkbox",
          externalID: 36,
        },
      ],
    },
    {
      externalGroupID: 10,
      groupRank: 5,
      text: "Cleaning and Maintenance",
      text_l1: "التنظيف والصيانة",
      text_l2: "备用电力",
      text_l3: "Очистка и тех. обслуживание",
      amenities: [
        {
          text: "Maintenance Staff",
          text_l1: "خدمات صيانة",
          text_l2: "清洁服务",
          text_l3: "Обслуживающий персонал",
          value: "1",
          rank: 2,
          slug: "maintenance-staff",
          format: "checkbox",
          externalID: 61,
        },
        {
          text: "Cleaning Services",
          text_l1: "خدمات تنظيف",
          text_l2: "清洁服务",
          text_l3: "Услуги по уборке",
          value: "1",
          rank: 3,
          slug: "cleaning-services",
          format: "checkbox",
          externalID: 73,
        },
      ],
    },
    {
      externalGroupID: 6,
      groupRank: 6,
      text: "Business and Security",
      text_l1: "الأعمال والأمن والحماية",
      text_l2: "双层玻璃窗",
      text_l3: "Бизнес и безопасность",
      amenities: [
        {
          text: "Security Staff",
          text_l1: "أمن و حماية",
          text_l2: "全部楼层",
          text_l3: "Сотрудники безопасности",
          value: "1",
          rank: 3,
          slug: "security-staff",
          format: "checkbox",
          externalID: 62,
        },
        {
          text: "CCTV Security",
          text_l1: "نظام كاميرات مراقبة",
          text_l2: "闭路电视安全",
          text_l3: "Безопасность видеонаблюдения",
          value: "1",
          rank: 4,
          slug: "cctv-security",
          format: "checkbox",
          externalID: 63,
        },
      ],
    },
    {
      externalGroupID: 8,
      groupRank: 8,
      text: "Technology",
      text_l1: "الخدمات التقنية",
      text_l2: "中央供暖",
      text_l3: "Технологии",
      amenities: [
        {
          text: "Broadband Internet",
          text_l1: "انترنت واسع النطاق",
          text_l2: "宽带网络",
          text_l3: "Широкополосный интернет",
          value: "1",
          rank: 1,
          slug: "broadband-internet",
          format: "checkbox",
          externalID: 26,
        },
        {
          text: "Satellite/Cable TV",
          text_l1: "كابل قنوات تلفزيونية",
          text_l2: "卫星电视/有线电视",
          text_l3: "Спутниковое/кабельное телевидение",
          value: "1",
          rank: 2,
          slug: "satellitecable-tv",
          format: "checkbox",
          externalID: 27,
        },
      ],
    },
    {
      externalGroupID: 7,
      groupRank: 9,
      text: "Miscellaneous",
      text_l1: "الخدمات العامة",
      text_l2: "中央空调",
      text_l3: "Разное",
      amenities: [
        {
          text: "Floor",
          text_l1: "طابق",
          text_l2: "楼层",
          text_l3: "Пол",
          value: "2",
          rank: 8,
          slug: "floor",
          format: "number",
          externalID: 13,
        },
        {
          text: "Nearby Shopping Malls",
          text_l1: "مراكز تسوق قريبة",
          text_l2: "泊车位",
          text_l3: "Ближайшие торговые центры",
          value: "Blue Mart",
          rank: 12,
          slug: "nearby-shopping-malls",
          format: "text",
          externalID: 57,
        },
        {
          text: "Other Nearby Places",
          text_l1: "أماكن قريبة أخرى",
          text_l2: "24小时礼宾服务",
          text_l3: "Другие близлежащие места",
          value: "Garden",
          rank: 20,
          slug: "other-nearby-places",
          format: "text",
          externalID: 60,
        },
        {
          text: "View",
          text_l1: "مطل",
          text_l2: "景观",
          text_l3: "Вид",
          value: "Swimming Pool",
          rank: 22,
          slug: "view",
          format: "text",
          externalID: 2,
        },
      ],
    },
  ],
  phoneNumber: {
    mobile: "+971589159379",
    phone: "+97143388004",
    whatsapp: "971545695868",
    phoneNumbers: ["+97143388004"],
    mobileNumbers: ["+971589159379"],
  },
  contactName: "Ahsan Zain Eddin",
  agency: {
    id: 29551757,
    objectID: 29551757,
    name: "Your Keys Holiday Homes",
    name_l1: "يور كيز هوليداي هومز رينتال",
    name_l2: "Your Keys Holiday Homes",
    name_l3: "Your Keys Holiday Homes",
    externalID: "9290",
    product: "premium",
    productScore: 2,
    licenses: [
      {
        number: "865561",
        authority: "DED",
      },
    ],
    logo: {
      id: 83780295,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/83780295/40f206ab5d1c4021832a1ee8ad194b55",
    },
    slug: "your-keys-holiday-homes-9290",
    slug_l1: "your-keys-holiday-homes-9290",
    slug_l2: "your-keys-holiday-homes-9290",
    slug_l3: "your-keys-holiday-homes-9290",
    tr: 3,
    tier: 3,
    roles: [],
    active: true,
    createdAt: "2019-12-29T05:18:05+00:00",
    commercialNumber: null,
    shortNumber: null,
    performanceCohort: "well_achieving",
  },
  active: false,
  hasExactGeography: true,
  verification: {
    status: "unverified",
    type: "manual",
    eligible: true,
    comment: null,
    updatedAt: 1695456390.84944,
    verifiedAt: 1667194187,
    visitedAt: null,
    trucheckedAt: 0,
  },
  isVerified: false,
  completionStatus: "completed",
  occupancyStatus: "vacant",
  randBoostScore: 440,
  randBoostScore_l1: 440,
  randBoostScore_l2: 373,
  randBoostScore_l3: 373,
  furnishingStatus: null,
  extraFields: {},
  type: "property",
  cityLevelScore: 3,
  indyScore: 440,
  indyScore_l1: 440,
  indyScore_l2: 373,
  indyScore_l3: 373,
  hasMatchingFloorPlans: true,
  hidePrice: false,
  locationPurposeTier: 1,
  plotArea: null,
};
