export const DemoSearchSuggestions = [
  {
    id: 3,
    name: "Abu Dhabi",
    name_l1: "أبوظبي",
    name_l2: "阿布扎比",
    name_l3: "Абу-Даби",
    externalID: "6020",
    slug: "/abu-dhabi",
    slug_l1: "/abu-dhabi",
    slug_l2: "/abu-dhabi",
    slug_l3: "/abu-dhabi",
    _geoloc: {
      lat: 23.379725784884,
      lng: 52.959231626126,
    },
    geography: {
      lat: 23.379725784884,
      lng: 52.959231626126,
    },
    geo_point: [52.959231626126, 23.379725784884],
    level: 1,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
    ],
    adCount: 66021,
    aliases: [],
    type: null,
    hasBuilding: false,
    trackID: "6020",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "3",
    _highlightResult: {
      name: {
        value: "<em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: true,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Абу-Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "6020",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 399,
    name: "Shams Abu Dhabi",
    name_l1: "شمس أبوظبي",
    name_l2: "沙姆斯-阿布扎比",
    name_l3: "Шамс Абу Даби",
    externalID: "7766",
    slug: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
    slug_l1: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
    slug_l2: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
    slug_l3: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
    _geoloc: {
      lat: 24.50685,
      lng: 54.407687,
    },
    geography: {
      lat: 24.50685,
      lng: 54.407687,
    },
    geo_point: [54.407687, 24.50685],
    level: 3,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 394,
        level: 2,
        externalID: "6232",
        name: "Al Reem Island",
        name_l1: "جزيرة الريم",
        name_l2: "阿尔雷姆岛",
        name_l3: "Остров Аль Рим",
        slug: "/abu-dhabi/al-reem-island",
        slug_l1: "/abu-dhabi/al-reem-island",
        slug_l2: "/abu-dhabi/al-reem-island",
        slug_l3: "/abu-dhabi/al-reem-island",
        type: "neighbourhood",
      },
      {
        id: 399,
        level: 3,
        externalID: "7766",
        name: "Shams Abu Dhabi",
        name_l1: "شمس أبوظبي",
        name_l2: "沙姆斯-阿布扎比",
        name_l3: "Шамс Абу Даби",
        slug: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
        slug_l1: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
        slug_l2: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
        slug_l3: "/abu-dhabi/al-reem-island/shams-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 4719,
    aliases: [],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "7766",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "399",
    _highlightResult: {
      name: {
        value: "Shams <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "شمس أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "沙姆斯-阿布扎比",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Шамс Абу Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "7766",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6232",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "7766",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/shams-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/shams-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/shams-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/shams-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 3490,
    name: "Najmat Abu Dhabi",
    name_l1: "نجمة ابوظبي",
    name_l2: "阿布扎比纳吉马特",
    name_l3: "Наджмат Абу-Даби",
    externalID: "6698",
    slug: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
    slug_l1: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
    slug_l2: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
    slug_l3: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
    _geoloc: {
      lat: 24.490175,
      lng: 54.408835,
    },
    geography: {
      lat: 24.490175,
      lng: 54.408835,
    },
    geo_point: [54.408835, 24.490175],
    level: 3,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 394,
        level: 2,
        externalID: "6232",
        name: "Al Reem Island",
        name_l1: "جزيرة الريم",
        name_l2: "阿尔雷姆岛",
        name_l3: "Остров Аль Рим",
        slug: "/abu-dhabi/al-reem-island",
        slug_l1: "/abu-dhabi/al-reem-island",
        slug_l2: "/abu-dhabi/al-reem-island",
        slug_l3: "/abu-dhabi/al-reem-island",
        type: "neighbourhood",
      },
      {
        id: 3490,
        level: 3,
        externalID: "6698",
        name: "Najmat Abu Dhabi",
        name_l1: "نجمة ابوظبي",
        name_l2: "阿布扎比纳吉马特",
        name_l3: "Наджмат Абу-Даби",
        slug: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
        slug_l1: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
        slug_l2: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
        slug_l3: "/abu-dhabi/al-reem-island/najmat-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 885,
    aliases: [],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "6698",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "3490",
    _highlightResult: {
      name: {
        value: "Najmat <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "نجمة ابوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比纳吉马特",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Наджмат Абу-Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "6698",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6232",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-reem-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6698",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/najmat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/najmat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/najmat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-reem-island/najmat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 458,
    name: "Danet Abu Dhabi",
    name_l1: "دانة أبوظبي",
    name_l2: "阿布扎比达内特社区",
    name_l3: "Данет Абу-Даби",
    externalID: "6858",
    slug: "/abu-dhabi/danet-abu-dhabi",
    slug_l1: "/abu-dhabi/danet-abu-dhabi",
    slug_l2: "/abu-dhabi/danet-abu-dhabi",
    slug_l3: "/abu-dhabi/danet-abu-dhabi",
    _geoloc: {
      lat: 24.430076,
      lng: 54.435232,
    },
    geography: {
      lat: 24.430076,
      lng: 54.435232,
    },
    geo_point: [54.435232, 24.430076],
    level: 2,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 458,
        level: 2,
        externalID: "6858",
        name: "Danet Abu Dhabi",
        name_l1: "دانة أبوظبي",
        name_l2: "阿布扎比达内特社区",
        name_l3: "Данет Абу-Даби",
        slug: "/abu-dhabi/danet-abu-dhabi",
        slug_l1: "/abu-dhabi/danet-abu-dhabi",
        slug_l2: "/abu-dhabi/danet-abu-dhabi",
        slug_l3: "/abu-dhabi/danet-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 363,
    aliases: ["Danat Abu Dhabi"],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "6858",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "458",
    _highlightResult: {
      name: {
        value: "Danet <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "دانة أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比达内特社区",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Данет Абу-Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "6858",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6858",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/danet-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/danet-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/danet-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/danet-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
      aliases: [
        {
          value: "Danat <em>Abu</em> <em>Dhabi</em>",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["abu", "dhabi"],
        },
      ],
    },
  },
  {
    id: 4995,
    name: "Rawdhat Abu Dhabi",
    name_l1: "روضة أبوظبي",
    name_l2: "阿布扎比罗达特",
    name_l3: "Равдхат Абу Даби",
    externalID: "9771",
    slug: "/abu-dhabi/rawdhat-abu-dhabi",
    slug_l1: "/abu-dhabi/rawdhat-abu-dhabi",
    slug_l2: "/abu-dhabi/rawdhat-abu-dhabi",
    slug_l3: "/abu-dhabi/rawdhat-abu-dhabi",
    _geoloc: {
      lat: 24.419551,
      lng: 54.464542,
    },
    geography: {
      lat: 24.419551,
      lng: 54.464542,
    },
    geo_point: [54.464542, 24.419551],
    level: 2,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 4995,
        level: 2,
        externalID: "9771",
        name: "Rawdhat Abu Dhabi",
        name_l1: "روضة أبوظبي",
        name_l2: "阿布扎比罗达特",
        name_l3: "Равдхат Абу Даби",
        slug: "/abu-dhabi/rawdhat-abu-dhabi",
        slug_l1: "/abu-dhabi/rawdhat-abu-dhabi",
        slug_l2: "/abu-dhabi/rawdhat-abu-dhabi",
        slug_l3: "/abu-dhabi/rawdhat-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 304,
    aliases: ["Rawdhat", "Al Rawdhat Abu Dhabi", "Rowdhat Abu Dhabi"],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "9771",
    roles: null,
    completionStatus: "completed",
    hasChildren: true,
    objectID: "4995",
    _highlightResult: {
      name: {
        value: "Rawdhat <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "روضة أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比罗达特",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Равдхат Абу Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "9771",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "9771",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/rawdhat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/rawdhat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/rawdhat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/rawdhat-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
      aliases: [
        {
          value: "Rawdhat",
          matchLevel: "none",
          matchedWords: [],
        },
        {
          value: "Al Rawdhat <em>Abu</em> <em>Dhabi</em>",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["abu", "dhabi"],
        },
        {
          value: "Rowdhat <em>Abu</em> <em>Dhabi</em>",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["abu", "dhabi"],
        },
      ],
    },
  },
  {
    id: 75817,
    name: "Louvre Abu Dhabi Residences",
    name_l1: "مساكن اللوفر أبوظبي",
    name_l2: "阿布扎比卢浮宫公寓",
    name_l3: "Резиденции Лувр Абу-Даби",
    externalID: "15293",
    slug: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
    slug_l1:
      "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
    slug_l2:
      "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
    slug_l3:
      "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
    _geoloc: {
      lat: 24.535094456259,
      lng: 54.402977747434,
    },
    geography: {
      lat: 24.535094456259,
      lng: 54.402977747434,
    },
    geo_point: [54.402977747434, 24.535094456259],
    level: 5,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 433,
        level: 2,
        externalID: "6863",
        name: "Saadiyat Island",
        name_l1: "جزيرة السعديات",
        name_l2: "萨迪亚特岛",
        name_l3: "Остров Садият",
        slug: "/abu-dhabi/saadiyat-island",
        slug_l1: "/abu-dhabi/saadiyat-island",
        slug_l2: "/abu-dhabi/saadiyat-island",
        slug_l3: "/abu-dhabi/saadiyat-island",
        type: "neighbourhood",
      },
      {
        id: 2188,
        level: 3,
        externalID: "9152",
        name: "Saadiyat Cultural District",
        name_l1: "المنطقة الثقافية في السعديات",
        name_l2: "萨迪亚特文化区",
        name_l3: "Саадият Культурал Дистрикт",
        slug: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district",
        slug_l1: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district",
        slug_l2: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district",
        slug_l3: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district",
        type: "neighbourhood",
      },
      {
        id: 75741,
        level: 4,
        externalID: "15244",
        name: "Saadiyat Grove",
        name_l1: "السعديات جروف",
        name_l2: "萨迪亚特丛林社区",
        name_l3: "Саадият Гроув",
        slug: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
        slug_l1:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
        slug_l2:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
        slug_l3:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
        type: "neighbourhood",
      },
      {
        id: 75817,
        level: 5,
        externalID: "15293",
        name: "Louvre Abu Dhabi Residences",
        name_l1: "مساكن اللوفر أبوظبي",
        name_l2: "阿布扎比卢浮宫公寓",
        name_l3: "Резиденции Лувр Абу-Даби",
        slug: "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
        slug_l1:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
        slug_l2:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
        slug_l3:
          "/abu-dhabi/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-abu-dhabi-residences",
      },
    ],
    adCount: 239,
    aliases: [],
    type: null,
    hasBuilding: false,
    trackID: "15293",
    roles: null,
    completionStatus: "off-plan",
    hasChildren: false,
    objectID: "75817",
    _highlightResult: {
      name: {
        value: "Louvre <em>Abu</em> <em>Dhabi</em> Residences",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "مساكن اللوفر أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比卢浮宫公寓",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Резиденции Лувр Абу-Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "15293",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6863",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/saadiyat-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/saadiyat-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/saadiyat-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/saadiyat-island",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "9152",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "15244",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "15293",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-<em>abu</em>-<em>dhabi</em>-residences",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-<em>abu</em>-<em>dhabi</em>-residences",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-<em>abu</em>-<em>dhabi</em>-residences",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/saadiyat-island/saadiyat-cultural-district/saadiyat-grove/louvre-<em>abu</em>-<em>dhabi</em>-residences",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 946,
    name: "ICAD - Industrial City Abu Dhabi",
    name_l1: "المدينة الصناعية في أبوظبي",
    name_l2: "ICAD - 阿布扎比工业城",
    name_l3: "ICAD - Индастриал Сити Абу Даби",
    externalID: "9714",
    slug: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
    slug_l1: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
    slug_l2: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
    slug_l3: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
    _geoloc: {
      lat: 24.349534,
      lng: 54.4999,
    },
    geography: {
      lat: 24.349534,
      lng: 54.4999,
    },
    geo_point: [54.4999, 24.349534],
    level: 3,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 945,
        level: 2,
        externalID: "6227",
        name: "Mussafah",
        name_l1: "مصفح",
        name_l2: "穆萨法赫",
        name_l3: "Муссафа",
        slug: "/abu-dhabi/mussafah",
        slug_l1: "/abu-dhabi/mussafah",
        slug_l2: "/abu-dhabi/mussafah",
        slug_l3: "/abu-dhabi/mussafah",
        type: "neighbourhood",
      },
      {
        id: 946,
        level: 3,
        externalID: "9714",
        name: "ICAD - Industrial City Abu Dhabi",
        name_l1: "المدينة الصناعية في أبوظبي",
        name_l2: "ICAD - 阿布扎比工业城",
        name_l3: "ICAD - Индастриал Сити Абу Даби",
        slug: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
        slug_l1: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
        slug_l2: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
        slug_l3: "/abu-dhabi/mussafah/icad--industrial-city-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 77,
    aliases: [],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "9714",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "946",
    _highlightResult: {
      name: {
        value: "ICAD - Industrial City <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "المدينة الصناعية في أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "ICAD - 阿布扎比工业城",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "ICAD - Индастриал Сити Абу Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "9714",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6227",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/mussafah",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/mussafah",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/mussafah",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/mussafah",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "9714",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/mussafah/icad--industrial-city-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/mussafah/icad--industrial-city-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/mussafah/icad--industrial-city-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/mussafah/icad--industrial-city-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 502,
    name: "Hills Abu Dhabi",
    name_l1: "تلال أبوظبي",
    name_l2: "阿布扎比山庄",
    name_l3: "Хиллс Абу Даби",
    externalID: "7875",
    slug: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
    slug_l1: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
    slug_l2: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
    slug_l3: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
    _geoloc: {
      lat: 24.4054575,
      lng: 54.467597,
    },
    geography: {
      lat: 24.4054575,
      lng: 54.467597,
    },
    geo_point: [54.467597, 24.4054575],
    level: 3,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 501,
        level: 2,
        externalID: "6208",
        name: "Al Maqtaa",
        name_l1: "المقطع",
        name_l2: "阿尔马克塔",
        name_l3: "Аль Мактаа",
        slug: "/abu-dhabi/al-maqtaa",
        slug_l1: "/abu-dhabi/al-maqtaa",
        slug_l2: "/abu-dhabi/al-maqtaa",
        slug_l3: "/abu-dhabi/al-maqtaa",
        type: "neighbourhood",
      },
      {
        id: 502,
        level: 3,
        externalID: "7875",
        name: "Hills Abu Dhabi",
        name_l1: "تلال أبوظبي",
        name_l2: "阿布扎比山庄",
        name_l3: "Хиллс Абу Даби",
        slug: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
        slug_l1: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
        slug_l2: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
        slug_l3: "/abu-dhabi/al-maqtaa/hills-abu-dhabi",
        type: "neighbourhood",
      },
    ],
    adCount: 62,
    aliases: [],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "7875",
    roles: null,
    completionStatus: "completed",
    hasChildren: true,
    objectID: "502",
    _highlightResult: {
      name: {
        value: "Hills <em>Abu</em> <em>Dhabi</em>",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "تلال أبوظبي",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比山庄",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Хиллс Абу Даби",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "7875",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "6208",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-maqtaa",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-maqtaa",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-maqtaa",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/al-maqtaa",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "7875",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-maqtaa/hills-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-maqtaa/hills-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-maqtaa/hills-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/al-maqtaa/hills-<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
  {
    id: 4982,
    name: "Abu Dhabi Gate City (Officers City)",
    name_l1: "مدينة بوابة أبوظبي (اوفيسرز سيتي)",
    name_l2: "阿布扎比门城（军官城）",
    name_l3: "Абу Даби Гейт Сити (Город офицеров)",
    externalID: "7137",
    slug: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
    slug_l1: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
    slug_l2: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
    slug_l3: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
    _geoloc: {
      lat: 24.393264,
      lng: 54.513441,
    },
    geography: {
      lat: 24.393264,
      lng: 54.513441,
    },
    geo_point: [54.513441, 24.393264],
    level: 2,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 4982,
        level: 2,
        externalID: "7137",
        name: "Abu Dhabi Gate City (Officers City)",
        name_l1: "مدينة بوابة أبوظبي (اوفيسرز سيتي)",
        name_l2: "阿布扎比门城（军官城）",
        name_l3: "Абу Даби Гейт Сити (Город офицеров)",
        slug: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
        slug_l1: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
        slug_l2: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
        slug_l3: "/abu-dhabi/abu-dhabi-gate-city-officers-city",
        type: "neighbourhood",
      },
    ],
    adCount: 50,
    aliases: ["Gate City Abu Dhabi", "Officers City"],
    type: "neighbourhood",
    hasBuilding: false,
    trackID: "7137",
    roles: null,
    completionStatus: "both",
    hasChildren: true,
    objectID: "4982",
    _highlightResult: {
      name: {
        value: "<em>Abu</em> <em>Dhabi</em> Gate City (Officers City)",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "مدينة بوابة أبوظبي (اوفيسرز سيتي)",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比门城（军官城）",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Абу Даби Гейт Сити (Город офицеров)",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "7137",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "7137",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/<em>abu</em>-<em>dhabi</em>-gate-city-officers-city",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/<em>abu</em>-<em>dhabi</em>-gate-city-officers-city",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/<em>abu</em>-<em>dhabi</em>-gate-city-officers-city",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/<em>abu</em>-<em>dhabi</em>-gate-city-officers-city",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
      aliases: [
        {
          value: "Gate City <em>Abu</em> <em>Dhabi</em>",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["abu", "dhabi"],
        },
        {
          value: "Officers City",
          matchLevel: "none",
          matchedWords: [],
        },
      ],
    },
  },
  {
    id: 15948,
    name: "Abu Dhabi National Exhibition Centre ADNEC",
    name_l1: "مركز أبو ظبي الوطني للمعارض",
    name_l2: "阿布扎比国家会展中心ADNEC",
    name_l3: "Национальный Выставочный Центр АДНЕК (Абу-Даби)",
    externalID: "12114",
    slug: "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
    slug_l1:
      "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
    slug_l2:
      "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
    slug_l3:
      "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
    _geoloc: {
      lat: 24.419066,
      lng: 54.436988,
    },
    geography: {
      lat: 24.419066,
      lng: 54.436988,
    },
    geo_point: [54.436988, 24.419066],
    level: 3,
    hierarchy: [
      {
        id: 1,
        level: 0,
        externalID: "5001",
        name: "UAE",
        name_l1: "الإمارات",
        name_l2: "阿联酋",
        name_l3: "ОАЭ",
        slug: "/uae",
        slug_l1: "/uae",
        slug_l2: "/uae",
        slug_l3: "/uae",
      },
      {
        id: 3,
        level: 1,
        externalID: "6020",
        name: "Abu Dhabi",
        name_l1: "أبوظبي",
        name_l2: "阿布扎比",
        name_l3: "Абу-Даби",
        slug: "/abu-dhabi",
        slug_l1: "/abu-dhabi",
        slug_l2: "/abu-dhabi",
        slug_l3: "/abu-dhabi",
      },
      {
        id: 4998,
        level: 2,
        externalID: "8101",
        name: "Capital Centre",
        name_l1: "كابيتال سنتر",
        name_l2: "首都中心",
        name_l3: "Капитал Центр",
        slug: "/abu-dhabi/capital-centre",
        slug_l1: "/abu-dhabi/capital-centre",
        slug_l2: "/abu-dhabi/capital-centre",
        slug_l3: "/abu-dhabi/capital-centre",
        type: "neighbourhood",
      },
      {
        id: 15948,
        level: 3,
        externalID: "12114",
        name: "Abu Dhabi National Exhibition Centre ADNEC",
        name_l1: "مركز أبو ظبي الوطني للمعارض",
        name_l2: "阿布扎比国家会展中心ADNEC",
        name_l3: "Национальный Выставочный Центр АДНЕК (Абу-Даби)",
        slug: "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
        slug_l1:
          "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
        slug_l2:
          "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
        slug_l3:
          "/abu-dhabi/capital-centre/abu-dhabi-national-exhibition-centre-adnec",
      },
    ],
    adCount: 30,
    aliases: [],
    type: null,
    hasBuilding: false,
    trackID: "12114",
    roles: null,
    completionStatus: "completed",
    hasChildren: false,
    objectID: "15948",
    _highlightResult: {
      name: {
        value: "<em>Abu</em> <em>Dhabi</em> National Exhibition Centre ADNEC",
        matchLevel: "full",
        fullyHighlighted: false,
        matchedWords: ["abu", "dhabi"],
      },
      name_l1: {
        value: "مركز أبو ظبي الوطني للمعارض",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l2: {
        value: "阿布扎比国家会展中心ADNEC",
        matchLevel: "none",
        matchedWords: [],
      },
      name_l3: {
        value: "Национальный Выставочный Центр АДНЕК (Абу-Даби)",
        matchLevel: "none",
        matchedWords: [],
      },
      externalID: {
        value: "12114",
        matchLevel: "none",
        matchedWords: [],
      },
      hierarchy: [
        {
          externalID: {
            value: "5001",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l1: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l2: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
          slug_l3: {
            value: "/uae",
            matchLevel: "none",
            matchedWords: [],
          },
        },
        {
          externalID: {
            value: "6020",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>",
            matchLevel: "full",
            fullyHighlighted: true,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "8101",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value: "/<em>abu</em>-<em>dhabi</em>/capital-centre",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value: "/<em>abu</em>-<em>dhabi</em>/capital-centre",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value: "/<em>abu</em>-<em>dhabi</em>/capital-centre",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value: "/<em>abu</em>-<em>dhabi</em>/capital-centre",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
        {
          externalID: {
            value: "12114",
            matchLevel: "none",
            matchedWords: [],
          },
          slug: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/capital-centre/<em>abu</em>-<em>dhabi</em>-national-exhibition-centre-adnec",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l1: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/capital-centre/<em>abu</em>-<em>dhabi</em>-national-exhibition-centre-adnec",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l2: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/capital-centre/<em>abu</em>-<em>dhabi</em>-national-exhibition-centre-adnec",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
          slug_l3: {
            value:
              "/<em>abu</em>-<em>dhabi</em>/capital-centre/<em>abu</em>-<em>dhabi</em>-national-exhibition-centre-adnec",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["abu", "dhabi"],
          },
        },
      ],
    },
  },
];
